fix
java.lang.NoClassDefFoundError: it/geosolutions/imageio/gdalframework/GDALImageReaderSpi
	at java.lang.ClassLoader.defineClass1(Native Method).....
	
due to missing gdal binding