log an error to find the root cause for bug #500 "possible important bug on Batik 1.6.1"
> javax.xml.transform.TransformerException: java.io.FileNotFoundException: file:/tmp/Parte%20-dialwdgg_4390.tif.aux.xml (File o directory non esistente)
> 	at org.apache.xalan.transformer.TransformerIdentityImpl.createResultContentHandler(TransformerIdentityImpl.java:263)
> 	at org.apache.xalan.transformer.TransformerIdentityImpl.transform(TransformerIdentityImpl.java:296)
> 	at org.openjump.core.rasterimage.GDALPamDataset.writeStatistics(GDALPamDataset.java:131)
> 	at org.openjump.core.rasterimage.TiffUtils.createStatsXml(TiffUtils.java:302)